services:
  - type: web
    name: current-affairs-quiz
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: NEWS_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
